apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "promlens.name" . }}
    chart: {{ template "promlens.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: promlens
spec:
  ports:
  - name: http
    port: {{ .Values.config.web.listen_address }}
    protocol: TCP
    targetPort: {{ .Values.config.web.listen_address }}
  selector:
    app: {{ template "promlens.name" . }}
