apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ template "imaginary.fullname" . }}
    {{- range $key, $value := .Values.additionalLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  name: {{ template "imaginary.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "imaginary.fullname" . }}
  targetCPUUtilizationPercentage: 80
