apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: {{ template "imaginary.fullname" . }}
    {{- range $key, $value := .Values.additionalLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  name: {{ template "imaginary.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ template "imaginary.fullname" . }}
