apiVersion: v1
kind: Secret
metadata:
  name: {{ template "imaginary.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "imaginary.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  apikey: {{ print .Values.apiKey | b64enc | quote  }}


