apiVersion: v1
kind: Service
metadata:
  name: {{ template "imaginary.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ .Release.Name | quote }}
  annotations:
    service.kubernetes.io/topology-aware-hints: {{ .Values.topologyAware | quote }}
spec:
  selector:
    app: {{ template "imaginary.fullname" . }}
  ports:
  - name: http
    port: {{ .Values.httpPort }}
    protocol: TCP
  type: {{ .Values.serviceType }}
