{{with .Values.gateway}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{.name}}
  namespace: {{ default "istio-ingress" .namespace }}
spec:
  selector:
{{toYaml .selector | indent 4}}
  servers:
{{toYaml .servers | indent 4}}
{{end}}
