{{ with .Values.secret }}
apiVersion: v1
data:
  client_id: {{ .client_id}}
  client_secret: {{ .client_secret}}
kind: Secret
metadata:
  name: iap-secret
  namespace: {{ default "istio-ingress" .namespace}}
type: Opaque
{{ end }}