apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gke-ingress.labels" . | nindent 4 }}
  annotations:
    {{- .Values.service.annotations | toYaml | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{ .Values.service.ports | toYaml | indent 4 }}
  selector:
    {{- include "gke-ingress.selectorLabels" . | nindent 4 }}