{{ with .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ default "istio-ingress" .namespace}}
  labels:
{{- .labels | toYaml | nindent 4 }}
  annotations:
{{- .annotations | toYaml | nindent 4 }}
spec:
  type: {{ .type }}
  ports:
{{ .ports | toYaml | indent 4 }}
  selector:
{{- .selector | toYaml | nindent 4 }}
{{ end }}