apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nobl9-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "nobl9-agent.name" . }}
    chart: {{ template "nobl9-agent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  client_id: {{ .Values.config.client_id | quote }}
  client_secret: {{ .Values.config.client_secret | quote }}
