{{- if .Values.config.proxyClientSaslEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-proxy.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "kafka-proxy.name" . }}
    helm.sh/chart: {{ include "kafka-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  jaas.config: {{ .Values.config.kafkaClient.jaas | b64enc | quote }}
{{- end }}
