apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kafka-proxy.name" . }}
    helm.sh/chart: {{ include "kafka-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    {{- range .Values.config.loadBalancerSourceRanges }}
    - {{ . | title | quote }}
    {{- end }}
  {{- if .Values.config.loadBalancerIP }}
  loadBalancerIP: {{ .Values.config.loadBalancerIP  }}
  {{- end }}
  ports:
  {{- range $index, $broker := .Values.config.kafkaClient.brokers }}
  - name: kafka-{{ add $index}}
    nodePort: {{ add 32400 $index }}
    port: {{ add 32400 $index }}
    targetPort: {{ add 32400 $index }}
  {{- end }}
  - name: metrics
    nodePort: 32480
    port: 9080
    targetPort: 9080
  selector:
    app.kubernetes.io/name: {{ include "kafka-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
