---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-01-12 - 16:26:45 +0000
  labels:
    helm.sh/chart: {{ include "keycloak-operator.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "keycloak-operator.fullname" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ include "keycloak-operator.chart" . }}
  name: {{ include "keycloak-operator.fullname" . }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "keycloak-operator.fullname" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  type: ClusterIP